apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ahutqg2x7-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ahutqg2x7-go 
  name: ahutqg2x7-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ahutqg2x7-go
    weight: 100 
