apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ahutqg2x7-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ahutqg2x7-go 
  name: ahutqg2x7-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ahutqg2x7-go 
